# Generated by Django 2.2 on 2020-02-27 03:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_follow'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follow',
            new_name='Favorite',
        ),
    ]
