# Generated by Django 2.2.6 on 2020-02-28 10:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_auto_20200227_0344'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favorite',
            new_name='Follow',
        ),
    ]
