version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yt-web
    command: gunicorn yatube.wsgi --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - db
  db:
    container_name: yt-db
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.db
  nginx:
    container_name: yt-nginx
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    ports:
      - 1337:80
    depends_on:
      - web
  cache:
    container_name: yt-cache
    image: redis:alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    expose:
      - 6379
volumes:
  postgres_data:
  static_volume:
  media_volume: