name: Yatube-CI

on:
  push:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install -r requirements.txt

      - name: Lint wiht flake8
        run: flake8 . --exclude=./api/migrations/*,./posts/migrations/*,./yatube/settings.py,./tests/*,./posts/tests.py

  build_and_push:
    name: Build and push to the Docker Hub
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Check out the repo
        uses: actions/checkout@v1

      - name: Push to the Docker Hub
        uses: docker/build-push-action@v1
        with:
          path: ./
          dockerfile: ./Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: evgfitil/yatube
          tag_with_ref: true
