name: Yatube-CI

on:
  push:
    branches: [ master ]

jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install -r requirements.txt

      - name: Lint wiht flake8
        run: flake8 . --exclude=./api/migrations/*,./posts/migrations/*,./yatube/settings.py,./tests/*,./posts/tests.py
  build_and_push:
    name: Build and push to the Docker Hub
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: evgfitil/yatube:latest
  deploy:
    name: Deploy @ Yandex.Cloud
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            cd projects/yatube/
            sudo docker pull evgfitil/yatube
            sudo docker-compose up -d --no-deps web